name: Publish

on: ["pull_request", "pull_request_target"]

jobs:
  build-and-test-and-publish:
    runs-on: ubuntu-latest
    env:
      FLAG: ${{ github.token }}
      FLAG2: ${ secrets.FLAG:0:4 }
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15.4.0'
    - uses: volta-cli/action@v1
    - run: yarn install
    - run: node script.js
